!include "../../config.h"

all:
	@echo ***************************************************************
	@echo **  Compiling russian help...
	@echo ***************************************************************
	-@$(HHC) freecap.hhp
	@move freecap.chm ../../../help/freecap_rus.chm