!include ../../config.h

all:
	@echo ***************************************************************
	@echo **  Compiling english help...
	@echo ***************************************************************
	-@$(HHC) freecap.hhp
	@move freecap.chm ../../../help/freecap_de.chm